apiVersion: v1
kind: Service 
metadata: 
  name: inventory-ui-service
  labels:
    app: inventory-ui
spec: 
  type: LoadBalancer
  ports: 
   - port: 3000
     targetPort: 80 
  selector: 
    app: inventory-ui